### ISSUE TITLE
"On this page" links are invalid

### ISSUE THREAD

**Issue by michalbundyra** [laminas/documentation-theme#15]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | master

#### Summary

https://docs.mezzio.dev/mezzio-swoole/

Not sure how links on the left side are generated, but these seems to be invalid.
On above page we have just "Installation" and "Support" but on the left side we have much more positions:

<img width="761" alt="image" src="https://user-images.githubusercontent.com/7423207/71994329-74588a00-3230-11ea-89a7-280f72a8a51a.png">

In other libraries we have usually two:

https://docs.mezzio.dev/mezzio-hal/

"Installation" and "Documentation" but also these seems to be invalid:

![image](https://user-images.githubusercontent.com/7423207/71994412-96520c80-3230-11ea-8d6c-ed6bfe0b8685.png)

**Comment by froschdesign** [comment]
@michalbundyra 
I found the problem. The headlines are taken from the readme file of the related repositories. Compare:

* https://github.com/mezzio/mezzio-swoole/blob/master/README.md
* https://github.com/mezzio/mezzio-hal/blob/master/README.md

It will be fixed with the next update of template which reorders the columns.
